### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [mouuff/PyPaymium#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary paymium -w /tmp/ext paymium==1.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting paymium==1.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/9f5/85d43fbde174b/paymium-1.0.tar.gz (3.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-5339ckrd/paymium/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-5339ckrd/paymium/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-5339ckrd/paymium/pip-egg-info
         cwd: /tmp/pip-wheel-5339ckrd/paymium/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-5339ckrd/paymium/setup.py", line 8, in <module>
        requirements = open("requirements.txt").read().splitlines()
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mouuff** [comment]
thank you!
